### PR TITLE
Setup Travis CI, sbt 1.2.8 & Scala 2.12.8

### LINKED ISSUE #4: Configure a travis-ci.com build
see https://github.com/lagom/shopping-cart-scala/issues/2 and related to https://github.com/playframework/play-meta/issues/13

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #4
Refs playframework/play-meta#13

### CODE REVIEW

**Comment by ignasi35** [comment]
🤦🏼‍♂️ I focused on maven in #3 and overlooked `sbt`-related changes.

**Comment by ignasi35** [comment]
@dwijnand did you want to send the PR to `1.4.x`instead of `1.5.x`? 

I guess the changes apply both to `1.4.x` and `1.5.x` and we can forward-port

**Comment by dwijnand** [comment]
No, I didn't... It's confusing enough to have:
* java vs scala repo...
* both mvn and sbt in the java repo...
* 1.4.x and 1.5.x branches...

**Comment by dwijnand** [comment]
1.4.x 433da27

**Pull request merged**
